### ISSUE TITLE
sorry Hannah, we made minor change to finufft interface

### ISSUE THREAD

**Issue by ahbarnett** [hannahlawrence/sinctransform#7]
Dear Hannah,

Sorry, as of finufft v 1.1 we changed the interface
from  finufft_default_opts(opts);
to finufft_default_opts(&opts);

If you change this in the six times it occurs in your C codes (two in each src/sinc?d.cpp) then your codes work again. Not worth a pull request.

PS Did you get a chance to change the tolerances to only divide by 10 instead of 1000, since the error metric changed (to relative rms error)? 

Hope all's well -   Cheers, Alex

**Comment by tanderson92** [comment]
Found this cool project (that might be useful to me!), then made #8 so I could use it, then found this issue. Thanks Hannah, this is awesome!

**Comment by ahbarnett** [comment]
Hi Thomas - I hope the sinc/FINUFFT combo helps you! - please cite
https://arxiv.org/abs/1808.06736
which just got accepted to SISC.
I will remind Hannah to accept your pull req.   Cheers, A

**Comment by tanderson92** [comment]
@ahbarnett Thanks, will do, congrats; might turn out my home-brew sinc transform solution is competitive or sufficient, but that's interesting too and worth a comparison.

**Comment by hannahlawrence** [comment]
Hi Thomas and Alex - so sorry about that, it appears I only fixed 3/6 of the instances way back when. Hope the library is helpful!
